name: 'Telegram Manual Approval'
description: 'Allows for manual approval of workflows via Telegram within chat.'
branding:
  icon: pause
  color: blue
inputs:
  TELEGRAM_KEY:
    description: 'Telegram Bot key'
    required: true
  TELEGRAM_CHAT_ID:
    description: 'Telegram chat ID to send message'
    required: true
  UPDATE_REQUESTS:
    description: 'Limit of updates (1 ~ 1 sec)'
    required: false
    default: "60"
  APPROVAL_TEXT:
    description: 'Text of message'
    required: false
    default: 'Please approve deployment:'
  APPROVAL_BUTTON:
    description: 'Text of approval button'
    required: false
    default: 'Approve'
  REJECT_BUTTON:
    description: 'Text of rejection button'
    required: false
    default: 'Reject'
  APPROVED_TEXT:
    description: 'Text of successful approved'
    required: false
    default: 'Approved!'
  REJECTED_TEXT:
    description: 'Text of successful rejected'
    required: false
    default: 'Rejected!'
  TIMEOUT_TEXT:
    description: 'Text of timeout'
    required: false
    default: 'Timeout!'
  ALLOW_RETRY_ON_TIMEOUT:
    description: 'Allow a retry button after timeout to resend approval request'
    required: false
    default: 'false'
  RETRY_BUTTON:
    description: 'Text of retry button'
    required: false
    default: 'Retry'
runs:
  using: "composite"
  steps:
    - run: $GITHUB_ACTION_PATH/main.sh --TELEGRAM_KEY ${{ inputs.TELEGRAM_KEY }} --TELEGRAM_CHAT_ID ${{ inputs.TELEGRAM_CHAT_ID }} --UPDATE_REQUESTS ${{ inputs.UPDATE_REQUESTS }} --APPROVAL_TEXT "${{ inputs.APPROVAL_TEXT }}" --APPROVAL_BUTTON "${{ inputs.APPROVAL_BUTTON }}" --REJECT_BUTTON "${{ inputs.REJECT_BUTTON }}" --APPROVED_TEXT "${{ inputs.APPROVED_TEXT }}" --REJECTED_TEXT "${{ inputs.REJECTED_TEXT }}" --TIMEOUT_TEXT "${{ inputs.TIMEOUT_TEXT }}" --ALLOW_RETRY_ON_TIMEOUT ${{ inputs.ALLOW_RETRY_ON_TIMEOUT }} --RETRY_BUTTON "${{ inputs.RETRY_BUTTON }}"
      shell: bash
