name: 'Telegram Manual Approval'
description: 'Allows for manual approval of workflows via Telegram within chat.'
branding:
  icon: pause
  color: blue
inputs:
  TELEGRAM_KEY:
    description: 'Telegram Bot key'
    required: true
  TELEGRAM_CHAT_ID:
    description: 'Telegram chat ID to send message'
    required: true
  UPDATE_REQUESTS:
    description: 'Limit of updates (1 ~ 1 sec)'
    required: false
    default: "60"
  APPROVAL_TEXT:
    description: 'Text of message'
    required: false
    default: 'Please approve deployment:'
  APPROVAL_BUTTON:
    description: 'Text of approval button'
    required: false
    default: 'Approve'
  REJECT_BUTTON:
    description: 'Text of rejection button'
    required: false
    default: 'Reject'
  APPROVED_TEXT:
    description: 'Text of successful approved'
    required: false
    default: 'Approved!'
  REJECTED_TEXT:
    description: 'Text of successful rejected'
    required: false
    default: 'Rejected!'
  TIMEOUT_TEXT:
    description: 'Text of timeout'
    required: false
    default: 'Timeout!'
  ALLOW_GITHUB_RERUN_ON_TIMEOUT:
    description: 'Allow a GitHub workflow rerun button after timeout'
    required: false
    default: 'true'
  RERUN_BUTTON:
    description: 'Text of GitHub rerun button'
    required: false
    default: 'Rerun workflow'
  RERUN_TEXT:
    description: 'Text shown when rerun is requested'
    required: false
    default: 'Rerun requested.'
  RERUN_FAILED_TEXT:
    description: 'Text shown when rerun fails'
    required: false
    default: 'Rerun failed.'
  GITHUB_TOKEN:
    description: 'GitHub token used to rerun workflows'
    required: false
    default: ''
  RERUN_WORKFLOW_FILE:
    description: 'Workflow file to dispatch on rerun (e.g. deploy.yml)'
    required: false
    default: ''
  RERUN_REF:
    description: 'Ref to use for workflow dispatch (branch or tag)'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - run: $GITHUB_ACTION_PATH/main.sh --TELEGRAM_KEY ${{ inputs.TELEGRAM_KEY }} --TELEGRAM_CHAT_ID ${{ inputs.TELEGRAM_CHAT_ID }} --UPDATE_REQUESTS ${{ inputs.UPDATE_REQUESTS }} --APPROVAL_TEXT "${{ inputs.APPROVAL_TEXT }}" --APPROVAL_BUTTON "${{ inputs.APPROVAL_BUTTON }}" --REJECT_BUTTON "${{ inputs.REJECT_BUTTON }}" --APPROVED_TEXT "${{ inputs.APPROVED_TEXT }}" --REJECTED_TEXT "${{ inputs.REJECTED_TEXT }}" --TIMEOUT_TEXT "${{ inputs.TIMEOUT_TEXT }}" --ALLOW_GITHUB_RERUN_ON_TIMEOUT ${{ inputs.ALLOW_GITHUB_RERUN_ON_TIMEOUT }} --RERUN_BUTTON "${{ inputs.RERUN_BUTTON }}" --RERUN_TEXT "${{ inputs.RERUN_TEXT }}" --RERUN_FAILED_TEXT "${{ inputs.RERUN_FAILED_TEXT }}" --RERUN_WORKFLOW_FILE "${{ inputs.RERUN_WORKFLOW_FILE }}" --RERUN_REF "${{ inputs.RERUN_REF }}"
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN || github.token }}
